services:
  redis-resolver:
    image: "redis:latest"
    container_name: "redis-resolver"
    ports:
      - "6379:6379"
    command: redis-server --databases 1
    restart: always

  redis-auth:
    image: "redis:latest"
    container_name: "redis-auth"
    ports:
      - "6380:6379"
    command: redis-server --databases 1
    restart: always

  redis-tld:
    image: "redis:latest"
    container_name: "redis-tld"
    ports:
      - "6381:6379"
    command: redis-server --databases 1
    restart: always

  python-dns:
    build: .
    container_name: "python-dns-server"
    ports:
      - "1053:1053/udp"
      - "1053:1053/tcp"
    environment:
      - REDIS_RESOLVER_HOST=redis-resolver
      - REDIS_AUTH_HOST=redis-auth
      - REDIS_TLD_HOST=redis-tld
      - LOG_LEVEL=DEBUG
    depends_on:
      - redis-resolver
      - redis-auth
      - redis-tld
    restart: always
